import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Navbar from "@/Components/NavBar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rick And Morty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style="--tg-color-scheme: light; --tg-theme-bg-color: #ffffff; --tg-theme-section-bg-color: #ffffff; --tg-theme-secondary-bg-color: #f0f0f0; --tg-theme-text-color: #222222; --tg-theme-hint-color: #a8a8a8; --tg-theme-link-color: #2678b6; --tg-theme-button-color: #50a8eb; --tg-theme-button-text-color: #ffffff; --tg-theme-header-bg-color: #527da3; --tg-theme-accent-text-color: #1c93e3; --tg-theme-section-header-text-color: #3a95d5; --tg-theme-subtitle-text-color: #82868a; --tg-theme-destructive-text-color: #cc2929; --tg-theme-section-separator-color: #d9d9d9; --tg-viewport-height: 100vh; --tg-viewport-stable-height: 100vh;"
    >
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>
        {/* Render the Navbar component */}
        <div style={{ touchAction: "none" }}>
          <Navbar />
        </div>

        {/* Render the page content */}
        {children}
      </body>
    </html>
  );
}
